### ISSUE TITLE
Crash after 935 calls of login page

### ISSUE THREAD

**Issue by dr-br** [jupyterhub/nativeauthenticator#124]
### Bug description
It is only possible to call the login page 935 times. The 936th attempt fails, leading to a white (completely empty) login page.

#### Expected behaviour
I want to be able to login (or load the login page) an infinite number of times.

#### Actual behaviour
White login page when trying to reload the login page the 936th time.

### How to reproduce
Either by clicking 936 times on browser refresh, or by using apache benchmark tool e.g. like so:
```
ab -c100 -n936 http://0.0.0.0:8000/hub/login
```
The page load frequency does not affect crash behavior. Only the number of login attempts / page loads.

### Your personal set up
- Create container image with the latest jupyterhub image and install nativeauthenticator.  
Dockerfile:
  ```
  ARG JUPYTERHUB_VERSION=latest
  FROM jupyterhub/jupyterhub:${JUPYTERHUB_VERSION}
  RUN pip install --no-cache dockerspawner
  RUN pip install --no-cache jupyterhub-nativeauthenticator
  ```
- Configure JupyterHub + Authenticator. Relevant entries are:
  ```
  c.JupyterHub.authenticator_class = 'nativeauthenticator.NativeAuthenticator'
  c.Authenticator.open_signup = True
  ```
- Start JupyterHub (in swarm mode in my case)
  - docker-compose.yaml 
    ```
    version: "3"
    services:
      hub:
        image: myHub:latest
        build:
          context: "."
          dockerfile: "./Dockerfile"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "./jupyterhub_srv/:/srv/jupyterhub/"
          - "./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py"
        networks:
          - jupyterhub-net
        ports:
          - "8000:8000"
          - "8081:8081"
    networks:
      jupyterhub-net:
        driver: overlay
    ```
  - Start
    ```
    docker swarm init
    docker-compose up
    ```
 - OS: Linux
 - Version: `jupyterhub --version` 1.2.1

### Attachments
- JupyterHub log starting at 933th page load
[logfile.txt](https://github.com/jupyterhub/nativeauthenticator/files/5536231/logfile.txt)
