### ISSUE TITLE
Not able to get Open Signup working on Kubernetes

### ISSUE THREAD

**Issue by chinmaychandak** [jupyterhub/nativeauthenticator#132]
Thank you for such an amazing project!

For JupyterHub on K8s, I am figuring out why NativeAuthenticator's `open_signup` isn't working. Here's my Helm chart config. Can someone please help? I am sure I am doing something incorrectly; the most recent docs are for JupyterHub Helm Chart v0.11+, while I'm still on 0.10.6. Does this feature not work with this version?

```
auth:
  type: "custom"
  custom:
    className: "nativeauthenticator.NativeAuthenticator"
  NativeAuthenticator:
    open_signup: true
```

P.S: Posted on Gitter/Discourse, but did not receive any response, so hoping someone here can help me out. :)

**Comment by lambdaTotoro** [comment]
Heya @chinmaychandak!
I must say I myself have not worked with Kubernetes before, so I might not be the one to talk to. But could you clarify what exactly you mean by open signup "not working"? And did you specify in the JupyterHub config (I'm assuming Kubernetes doesn't make that superfluous?)?

**Comment by chinmaychandak** [comment]
Thank you so much for responding @lambdaTotoro! 

> could you clarify what exactly you mean by open signup "not working"

Basically, even after deploying the open signup config as I showed above, the admins still need to authorize users that sign up. 

> And did you specify in the JupyterHub config (I'm assuming Kubernetes doesn't make that superfluous?)?

Right, so all one should need to do is specify the open signup config in the Helm config and nothing else. I'm sure it's just a matter of getting the config right, so was trying [this](https://native-authenticator.readthedocs.io/en/latest/options.html#open-signup) out.

@consideRatio, sorry for roping you in here, but I noticed that you worked on a substantial portion of upgrading ZTJWK from 0.10.6 to 0.11+ and auth was quite a major portion of it. Could you please help me out? I would really appreciate it if you could spare a couple of minutes, just wondering if upgrading to 0.11 is the only way to get things working. :)

**Comment by consideRatio** [comment]
Hi @chinmaychandak, being on 0.10.6, you should model your configuration after [this example](https://zero-to-jupyterhub.readthedocs.io/en/0.10.6/administrator/authentication.html#example-auth0-configuration) with regards to how you structure it.

I think it will become...

```yaml
auth:
  type: "custom"
  custom:
    className: "nativeauthenticator.NativeAuthenticator"
    config:
      open_signup: true
```
