### ISSUE TITLE
unable to import nativeauthenticator.NativeAuthenticator

### ISSUE THREAD

**Issue by bebosudo** [jupyterhub/nativeauthenticator#93]
I've been trying to integrate nativeauthenticator for the past couple of hours inside a kubernetes setup, but I keep getting messages like the following when the pod containing jhub is launched:

```
[C ... JupyterHub application:91] The 'authenticator_class' trait of <jupyterhub.app.JupyterHub object at 0x7fa9ff9fb208> instance must be a type, but 'nativeauthenticator.NativeAuthenticator' could not be imported
```

The Dockerfile I used to build this jhub is:
```dockerfile
FROM jupyterhub-k8s-hub-hotfix:722712477dd0
ARG  PKGUSER=jupyterhub
ARG  PKGNAME=nativeauthenticator
ARG  COMMIT=2fede2bfc109c9107064eb4a7c48dd4e4d6a79ee

# The image changes user to 1000, but we need to edit stuff as root.
USER root
RUN  apt update && apt install -y curl && apt-get clean \
       && curl -sL https://github.com/${PKGUSER}/${PKGNAME}/archive/${COMMIT}.tar.gz |tar -xz \
       && cd ${PKGNAME}-${COMMIT} \
       && pip3 --no-cache-dir install --upgrade wheel pip \
       && pip3 --no-cache-dir install --src /usr/local/lib/python3.6/dist-packages/ -e .

COPY jupyter_config.py /srv/jupyterhub_config.py

USER 1000
```

The base image ("hotfix") I'm using is:
```dockerfile
FROM jupyterhub/k8s-hub:0.8.2
# The image changes user to 1000, but we need to edit stuff as root.
USER root
COPY jupyterhub-hotfix.patch /
RUN  patch /usr/local/lib/python3.6/dist-packages/kubespawner/spawner.py /jupyterhub-hotfix.patch && rm /jupyterhub-hotfix.patch
USER 1000
```
This is due to a bug when jhub is used on k8s 1.16, see patch here: https://github.com/jupyterhub/kubespawner/issues/354#issuecomment-540844443, which I also report here:
```patch
72c72
<             key=lambda x: x.last_timestamp,
---
>             key=lambda x: x.last_timestamp and x.last_timestamp.timestamp() or 0.,
```

The jupyter_config.py has not been touched, and the helm configuration for the deployment is:
```yaml
hub:
  # Image will manage the user login and jupyterlab creation.
  image:
    name: jupyterhub-k8s-hub-native
    tag: 722712477dd0
  imagePullPolicy: Never

auth:
  type: "custom"
  custom:
    className: "nativeauthenticator.NativeAuthenticator"
```

Any idea why that error comes up?
If I run a shell in the "native" container I'm able to do `python3 -c 'import nativeauthenticator'` as well as e.g. `python3 -c 'import oauthenticator`.

**Comment by leportella** [comment]
@consideRatio could you please help us out here?

**Comment by consideRatio** [comment]
1. Let's install nativeauthenticator in the jupyterhub hub docker image.
2. You don't have that issue you describe with timestamp in the latest jupyterhub (beta.3 or even later development releases)

Then - let's think more about it all. I'll be back!

**Comment by bebosudo** [comment]
@leportella @consideRatio any news/update?

**Comment by consideRatio** [comment]
I'll go add it to the docker image right now as a break from my work :)

**Comment by consideRatio** [comment]
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1583

**Comment by consideRatio** [comment]
@bebosudo Try out version 0.9.0-beta.3.n040.hb5c8dce for k8s 1.16/1.17 compatebility and nativeauthenticator available

Configure it as it were a custom authenticator, im too time constrained to help more right now - thanks for exploring its use!

**Comment by bebosudo** [comment]
Hi, thanks for your work! Using release `0.9.0-beta.4.n000.h72e54ee` I was able to have a nativeauthenticator almost working.
The config I ended up using is the following, as I reported in another issue in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/84#issuecomment-597687633:

```yaml
hub:
  # Image that manages the user login and jupyterlab creation.
  # Use the same tag used when installing with helm.
  image:
    name: jupyterhub/k8s-hub
    tag: 0.9.0-beta.4.n000.h72e54ee

  services:
    testService:
      admin: true
      apiToken: "aec7d32df938c0f55e54f09244a350cb29ea612907ed4f07be13d9553d18a8e4"

auth:
  type: "custom"
  custom:
   className: "nativeauthenticator.NativeAuthenticator"
  admin:
    users:
      - admin1
  whitelist:
    users:
      - test1
      - test2

# other non-relevant stuff
```

My question is: how can I define password for the admins and users, if it's possible at all?
Is there any k8s Secret object I need to define?
I don't see any useful user management endpoint in the REST API doc: https://jupyterhub.readthedocs.io/en/stable/_static/rest-api/index.html

I'm fine with creating them from an external script, something that I could place in a CronJob and repeat every hour or so, to make sure they exist.

Moreover: what is a service in jhub?
If I now list the services I get also a `testService`, the one I just created to access the API, along with the cull service:
```console
$ curl -L  -H  "accept: application/json" -H "Authorization: token aec7d32df938c0f55e54f09244a350cb29ea612907ed4f07be13d9553d18a8e4" http://host:port/hub/api/services |python -m json.tool
{
    "cull-idle": {
        "admin": true,
        "command": [
            "python3",
            "/etc/jupyterhub/cull_idle_servers.py",
            "--url=http://127.0.0.1:8081/hub/api",
            "--timeout=3600",
            "--cull-every=600",
            "--concurrency=10"
        ],
        "info": {},
        "name": "cull-idle",
        "pid": 11,
        "prefix": "",
        "url": ""
    },
    "testService": {
        "admin": true,
        "command": [],
        "info": {},
        "name": "testService",
        "pid": 0,
        "prefix": "",
        "url": ""
    }
}
```

Could the password-setting operation be performed using a jhub service?
